# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_vx: 3
speed_lim_vy: 3
speed_lim_w: 10

accel_lim_vx: 0.3
accel_lim_vy: 0.3
accel_lim_w: 10

# Optional parameters
frequency: 20.0
decel_factor: 100.0
decel_factor_safety: 100.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 2
