base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
  max_vel_x: 0.7
  min_vel_x: 0.0
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 10
  acc_lim_x: 3.0
  acc_lim_y: 0

  holonomic_robot: false
  escape_vel: -0.2
  yaw_goal_tolerance: 2
  xy_goal_tolerance: 0.5

  sim_time: 2.0
  vx_samples: 5
  vtheta_samples: 10
  sim_granularity: 0.05
  angular_sim_granularity: 0.05

  pdist_scale: 0.8
  gdist_scale: 0.4
  occdist_scale: 0.01

  dwa: true
  publish_cost_grid_pc: true
  meter_scoring: true
  
  global_frame_id: /odometry/filtered

#Below params are just in move_base

controller_frequency: 10.0
