footprint: [[0.44, 0.38], [0.44,-0.38], [-0.44,-0.38], [-0.44,0.38]]

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: 
    topic: /scan
    sensor_frame: /scan
    data_type: LaserScan
    marking: true
    clearing: true
    #expected_update_rate: 5.0
    inf_is_valid: true
  obstacle_range: 6
  raytrace_range: 15

inflation_layer:
  inflation_radius: 0.35
  cost_scaling_factor: 10.0
