local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  origin_x: -3.5
  origin_y: -3.5
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
   #- {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
   - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
   - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

  sonar_layer: 
    topics: ['/ultrasonic1','/ultrasonic2','/ultrasonic3']
    clear_threshold: 0.4
    mark_threshold: 0.6
    clear_on_max_reading: true
    no_readings_timeout: 0.0
