set(_CATKIN_CURRENT_PACKAGE "cob_base_velocity_smoother")
set(cob_base_velocity_smoother_VERSION "0.7.5")
set(cob_base_velocity_smoother_MAINTAINER "Benjamin Maidel <bnm@ipa.fhg.de>")
set(cob_base_velocity_smoother_PACKAGE_FORMAT "2")
set(cob_base_velocity_smoother_BUILD_DEPENDS "boost" "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "roslint" "std_msgs")
set(cob_base_velocity_smoother_BUILD_EXPORT_DEPENDS "boost" "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "roslint" "std_msgs")
set(cob_base_velocity_smoother_BUILDTOOL_DEPENDS "catkin")
set(cob_base_velocity_smoother_BUILDTOOL_EXPORT_DEPENDS )
set(cob_base_velocity_smoother_EXEC_DEPENDS "boost" "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "roslint" "std_msgs")
set(cob_base_velocity_smoother_RUN_DEPENDS "boost" "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "roslint" "std_msgs")
set(cob_base_velocity_smoother_TEST_DEPENDS )
set(cob_base_velocity_smoother_DOC_DEPENDS )
set(cob_base_velocity_smoother_URL_WEBSITE "http://ros.org/wiki/cob_base_velocity_smoother")
set(cob_base_velocity_smoother_URL_BUGTRACKER "")
set(cob_base_velocity_smoother_URL_REPOSITORY "")
set(cob_base_velocity_smoother_DEPRECATED "")